name: PR
on: pull_request
jobs:
  PR_flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm i
        run: |
          npm install
      - name: lint
        run: |
          npm run lint
      - name: test
        run: |
          npm run test:coverage
      - name: build
        run: |
          npm run build
        env:
          CI: true
